cache:
  directories:
  - "$GOPATH/pkg/mod"
  - "$HOME/.cache/go-build"
language: go
go:
- 1.15.x
env:
  matrix:
  - GO111MODULE=on
  global:
  - secure: lSJJAU3EgbJZura/7lkn7d9a3tkBVz+KBOdYd6QAQPrG1pYYBCEtnrctdxPzkWjd6Kkb5PEKxvqaoq+EnzPKmXFEp/Uowe2sstCTHWN91f0hrf01Sa4ne0FQxnCmw6QyyOWuyi6eou4pwdVGa4HUJm5KtU714cUHzOa8EBQVAcwgdIbFbSb1UxRC1tCIeuPtmE4ZAIYz6QPNtVvlnRsyGw62HqgZ2yfxiB08ZFhiBUVxzZW0yinJUDSb45HOHqx9FPJ6wVOGhdpU11FZi+noKDvw4l7fRMEVN06R05LPWLNoWIhZdBtBTSJI2/pJ9kDFHNHOwkKSloH5pU7EMYlqPpLimmL8knbD2iSDro8jXGEiWkv0wxydtJyx7ILr4bjLp3FIj5o2bRGqe+1bMEnm17ivj2RaHS7P+6ijL9KiPdHQyzXJ33xpbZ8wyywZ2WcFbj+Gcv4NlnBTzAXjhf+kYv0K8aDc0+IJPG7hXfudd1mXN4Jx6yAFYs3p6lUKdBsQyM0csu/8gu9SZyTbQMjssZJe4NlivQVB3A8zxpSLz9kcjYlDKlpd/U8pLUyC9InwabAusx5bTbBw+RYCU67j6PeYDc9Ou5lTSwXib2qLHgduYnA5c49NFXC+5r819APhKb4ho4ORu5kaDJMJpsSIbs3J3gBQhNRx5qOIIz1Fduo=
  - secure: snoDp9E2yNP7QBU5qnFGan7eOMK+AbEd4POGp9eeFq2znDFQRTWyxNDUJx607IS1+EKfqJ099IPe23t+S4wNLt75AXEWo7r/IDuTOQA6u0HUrJa4HVYHIM6TxDCl1w/gCZrzfT64DO9IqBnkV4kTVJB4JwNfO5L7dtLXAQlg8vSFjqnDdIiZxBV48OLllZXBpVfz9xRjpwhpHNk45SIjY1+G3iSZ5r7IjyXiDk+G0ThzMqcj4JcWhRqdemXAkVyQCll4QebhHhtvR1FOPUFx/HLoDGrJvom8W60sWNWHak1OYDP6KlQRohuhFkE9GweAG/gENkVGmW7m5++x1R0QY54Az+9ZhDoMDp/bUQKVE8Ffq+LtcD4RMW5NmswNUzoNuJIAdfqXwXDmRabdawKNiKTNSGAWyvdVvMoFZEbUTFV2j464n5CS+CSvbkDyQnopwy7Z6TDwiVrx7BP//XIU1KMDe2v0kDQmBz/+qe2aexAAOokaPIvHrIZkqJIVNfivXTnngxUxICQs+nM9+9lcUVBqkvkilKRUxlmxazSCe2RhBdMiEiLxGhyley+jvdBUbjqWsHtmmK+n8TT7YRBBxu/kQI0FD9fYKy6XLrZG6scqFjheak4EcCBc+43EvqUM17U6Wa49mum6O51z4bkkQKLFtzFjRjVPKmwUiGLJTGY=
notifications:
  email:
    recipients:
    - newfarry@126.com
    on_success: always
addons:
  apt:
    packages:
    - snapcraft
services:
- docker
after_success:
- docker login -u=openiothub -p="$DOCKER_PASSWORD"
- snapcraft login --with snap.login
- rm snap.login
deploy:
- provider: script
  skip_cleanup: true
  script: git checkout . && curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_164ead62e292_key -iv $encrypted_164ead62e292_iv
  -in snap.login.enc -out snap.login -d
